theme: "minimal"

# Site Settings
title: "M. J. Haus"
subtitle: "WIP" # site tagline that appears below site title in masthead
name: "Miranda J. Haus name"
description: "Trying to get a website going."
