# Site Settings
title: M. J. Haus
subtitle: WIP # site tagline that appears below site title in masthead
author:
  name: Miranda J. Haus name
  email: hausmira@msu.edu
description: "Trying to get a website going."

# Build settings
remote_theme: jekyll-theme-modernist

#Theme settings
#minima:
#  skin: dark
